/* Fixed seed metadata exported from the Seed Library. */
const SUNFLOWER_SEED_CATALOG = Object.freeze([
  {"name":"Apple Seed","seedIcon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJAgMAAACd/+6DAAAACVBMVEUAAADpQUqyKDcAKEvxAAAAAXRSTlMAQObYZgAAACtJREFUCNdj4GpgYFBNYGCYGcHAMC2MgWHq1AYG1dQGBs7IBgamUKDkKgYAiqUIBE1ZIjIAAAAASUVORK5CYII=","seasons":["autumn","winter"],"treeIconUrl":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAOCAYAAAD5YeaVAAAAAXNSR0IArs4c6QAAAOpJREFUKJGFkb9qAkEQh78RTZ+Aj+BZpRDBQIoFrWx8A7HKY6RL5TtcJZY2ljZXXJHiRESsPDsrQVBSCQo3abzNSvbwV82fb36z7MADmWFXzbCrAPIIrJkKANv4Wgzn4Da+ArBfXyj5wKDf0dzNVdkH93Zn5q9P7NcXW0vHkVh4FDQ1j1e3tZ/JDwCDdCHWeRQ0tVN9BuDlvQXTGV9vbY7V5Jajg3Qh4oIA0eFkY9dgMp39f7M7mOv4nQBQCiW7c/MpOpwIJfv7uqIBt14uavgkAKbe0A/13geAUDLizVLsuU29oUVwvFkKwC8LIliXv5yGnAAAAABJRU5ErkJggg==","type":"fruit"},
  {"name":"Artichoke Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/artichoke/seed.png","seasons":["autumn"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/artichoke/crop.png","type":"crop"},
  {"name":"Banana Plant","seedIcon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAoAAAAKCAMAAAC67D+PAAAAAXNSR0IArs4c6QAAABhQTFRFAAAAwoVp5KZyuG9QY8dNJlxCTadvPolIBHEHkwAAAAh0Uk5TAP/////////VylQyAAAAL0lEQVQImWNgwA7Y2NigBDsLCwsbG5BgZ2AFkSA+KwMDKysrOzuQgCiH0ahMDAAAMG0Ax0M6L2sAAAAASUVORK5CYII=","seasons":["autumn","summer"],"treeIconUrl":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA0AAAAOCAYAAAD0f5bSAAAAAXNSR0IArs4c6QAAAM5JREFUKJGFka8OgzAQxr+SEoKdwaNmlkyQbFWYvdAS0heYIzO8xRRPMDMFcsk8HoMlGG6i0BRo6JnL3X2/+/oHcESWCspSQWaPu4DbOZoqQc9PxZyQEikXBSvQcx3vcWkBAO9vq3u70FgmFNxTDc6Z7QEQJ6D6QWcAQ93ZnTRghlHzjdgUTNvXwa1iE7As8MYyIVn4y+EOAAB8qDsA0XJgc4R6hDBvGAOAXsYUXA+QhY/8dbRunwF9pzBvWC9BG0cLAKz+qZcxbYhpqVn/Adu2YYOCjYxqAAAAAElFTkSuQmCC","type":"fruit"},
  {"name":"Barley Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/barley/seed.png","seasons":["autumn","spring"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/barley/crop.png","type":"crop"},
  {"name":"Beetroot Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/beetroot/seed.png","seasons":["summer","winter"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/beetroot/crop.png","type":"crop"},
  {"name":"Bloom Seed","seedIcon":"data:image/webp;base64,UklGRk4AAABXRUJQVlA4TEIAAAAvBUABECdAmG00rgnN/94HIiQg/PRctIQw22hu85j//wBu/gPg3vMuAwWRbNBpnwRE8Aq8RwIR/Q87shIvtG7yzgA=","seasons":["autumn","spring","summer","winter"],"treeIconUrl":"","type":"flower"},
  {"name":"Blueberry Seed","seedIcon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJAgMAAACd/+6DAAAADFBMVEUAAAAaYc0RTYkDl92BEBmNAAAAAXRSTlMAQObYZgAAAB9JREFUCNdjYFrAwMD9g4FBN46BYWt4AwwD+WBxkDwAo38JBSnOMAkAAAAASUVORK5CYII=","seasons":["spring","winter"],"treeIconUrl":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAAAXNSR0IArs4c6QAAAN9JREFUKJF1kTEKwjAYhb9IpYu3KL2AgyBCD6B0cPIAPUCXgpOTk5AlB/AATg6iByhIwcELFG/hEhziUKNJ1DeFvPe/935+QYBBtjb2fa9XIuSjUBxXpftlwiHhiZMp+nYCIE6mME/RUrHYXNiODwKgF0YCBCm09YOiyc07oWhys1uOOlcHNg1gODuTZn2ioslNWz88ga3mJl0lpNmlW/p6nHiklqpL27cfk6pkt1T0bBUtFVoq2LfEVekJXXhLhyTQGTi7vQdshX/QUnGvVyJ6Hca4LpYEvq7uHS4kf+EJiDFhlnltoFMAAAAASUVORK5CYII=","type":"fruit"},
  {"name":"Broccoli Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/brocolli/seed.png","seasons":["autumn"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/brocolli/crop.png","type":"crop"},
  {"name":"Cabbage Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/cabbage/seed.png","seasons":[],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/cabbage/crop.png","type":"crop"},
  {"name":"Carrot Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/carrot/seed.png","seasons":["autumn","spring"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/carrot/crop.png","type":"crop"},
  {"name":"Cauliflower Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/cauliflower/seed.png","seasons":["summer","winter"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/cauliflower/crop.png","type":"crop"},
  {"name":"Celestine Seed","seedIcon":"data:image/webp;base64,UklGRlQAAABXRUJQVlA4TEgAAAAvBkABECdAmG00/8cEB3CHRCZtU/92KqC2dg3CbKMR7D+8cz+Q+Q/Avi6le1DQRpIanQMj8Ar+XgBG9D/4zo7LyOkr23c/+A4=","seasons":[],"treeIconUrl":"data:image/webp;base64,UklGRmgAAABXRUJQVlA4TFsAAAAvB8ABEDdAFmAygf4MEslfI4s4CDUwLo4c/iJoL4cRCFDkhwFu2W6BB/MfgL2rkcOxV7KDokhSXE1bhQIKDfzhkoHk4ATkiP4HYoTxJ5mriK5y+Kf6R7LWCDECAA==","type":"fruit"},
  {"name":"Clover Seed","seedIcon":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4TEYAAAAvBYABECdAkG0zf7EN4A5XUpC2ATP/xqbpQ5BtM4FBjvkeZ5j/APgrJt0oKGgjhQ0/wwAWCA5AwIzof+DRpuFbfpXXr3gA","seasons":["autumn"],"treeIconUrl":"","type":"flower"},
  {"name":"Corn Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/corn/seed.png","seasons":["spring"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/corn/crop.png","type":"crop"},
  {"name":"Duskberry Seed","seedIcon":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4TEUAAAAvBkABECdAkG0zhU3j/lj3Ici22WTmz3KNSxBk24xlU7n15eY/AGt9Ut9BISRJbnTW4AJBILj7j+h/4MJ+sm9Ur2Ud4AIA","seasons":[],"treeIconUrl":"data:image/webp;base64,UklGRmQAAABXRUJQVlA4TFgAAAAvB8ABEDdAFmAyhrmF3x1FHgQCFNnAWO9T1EYKtK91cQBacI0qHMx/AOCekpIZ3fkf1AQA0orCFWBWsAAaYP6AWsGI/ge8B+SXy7/fXPrdfp226iFEB+8B","type":"fruit"},
  {"name":"Edelweiss Seed","seedIcon":"data:image/webp;base64,UklGRlQAAABXRUJQVlA4TEgAAAAvBYABECegkG0EaP5s9xmdhpq2DZjyZ9V7QqqCtm2Y8sd39rFs/gPA/8UzpYygoI0UNvwMA1ggOAABM6L/gUebhm/5VV6/4gE=","seasons":["winter"],"treeIconUrl":"","type":"flower"},
  {"name":"Eggplant Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/eggplant/seed.png","seasons":["summer"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/eggplant/crop.png","type":"crop"},
  {"name":"Gladiolus Seed","seedIcon":"data:image/webp;base64,UklGRk4AAABXRUJQVlA4TEEAAAAvBYABECdAkG2bG8oEZvCcMNs4NoH9dwCnIG0DFu7L2vwHwPYaNX9BQSQbdPi9Bh8JaGBUENH/gKHnXvWlJzJhAAA=","seasons":["summer"],"treeIconUrl":"","type":"flower"},
  {"name":"Kale Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/kale/seed.png","seasons":["spring","winter"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/kale/crop.png","type":"crop"},
  {"name":"Lavender Seed","seedIcon":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4TEUAAAAvBYABECegoG0bpvxpFcDduAkECP9Rijwgk7apfy8VVGZlx/wHwP2PWORAQRspbPgZBrBAcAACZkT/A482Dd/yq7x+xQMA","seasons":["spring"],"treeIconUrl":"","type":"flower"},
  {"name":"Lemon Seed","seedIcon":"data:image/webp;base64,UklGRlQAAABXRUJQVlA4TEcAAAAvBUABECdAkG0zf6JRDOQS1yDMNpo/4gwmcN8jyLaZv8DABnGMz38A/jdltoGCRlLcNM0AOGgGCAb4EtH/+AGlVOplvTHwBQA=","seasons":["summer","winter"],"treeIconUrl":"data:image/webp;base64,UklGRpAAAABXRUJQVlA4TIMAAAAvCUACEFegKLYN6iUxCuhfwU4LBf5WaiiOJANaBOCnZCH/0G5GAiAhsYPGeTY4w+gEm9n5DwD+fyJiy30zOZrLQ8SJ1NgG2ES27eT8T6r5DnhIyPR/EPA6ukxNhwQkICEpjuh/cCZw/EPEc4vydC6LrkJSHcvc6egLUfqyWBh9scC+xwA=","type":"fruit"},
  {"name":"Lily Seed","seedIcon":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4TEUAAAAvBUABECdAkG0zf5cBDOkU1yDIthnDPOYvcp+TSdvUv4qKLHs3/wH4f41LCgraSGGzLAVIAAm8AFZE/4O+Owy+yP2yfwIA","seasons":["autumn","spring","summer","winter"],"treeIconUrl":"","type":"flower"},
  {"name":"Lunara Seed","seedIcon":"data:image/webp;base64,UklGRlIAAABXRUJQVlA4TEYAAAAvBkABECdAmG00hrkN/96nRCBps2XY+0c9hNlGew1kZsd5cvMfgH9Lmu2goI0kNToHSsDA/b8AjOh/8J3djzXTa4bvuPAd","seasons":[],"treeIconUrl":"data:image/webp;base64,UklGRloAAABXRUJQVlA4TE0AAAAvB8ABECdAmG00hrkN/96nRCBps2XY+0c9hNlGew1kZsd5cvMfgH9Lmu2goI0kNXwPBkjB/Rs4EIAR/Q+oAlsyr1DepNQl8eWFIU6oAgA=","type":"fruit"},
  {"name":"Onion Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/onion/seed.png","seasons":["winter"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/onion/crop.png","type":"crop"},
  {"name":"Parsnip Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/parsnip/seed.png","seasons":["winter"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/parsnip/crop.png","type":"crop"},
  {"name":"Pepper Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/pepper/seed.png","seasons":["summer"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/pepper/crop.png","type":"crop"},
  {"name":"Potato Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/potato/seed.png","seasons":["autumn","summer","winter"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/potato/crop.png","type":"crop"},
  {"name":"Pumpkin Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/pumpkin/seed.png","seasons":["autumn"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/pumpkin/crop.png","type":"crop"},
  {"name":"Radish Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/radish/seed.png","seasons":["summer"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/radish/crop.png","type":"crop"},
  {"name":"Rhubarb Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/rhubarb/seed.png","seasons":["spring"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/rhubarb/crop.png","type":"crop"},
  {"name":"Saltwort Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/saltwort/seed.png","seasons":[],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/saltwort/crop.png","type":"crop"},
  {"name":"Soybean Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/soybean/seed.png","seasons":["autumn","spring"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/soybean/crop.png","type":"crop"},
  {"name":"Sunflower Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/sunflower/seed.png","seasons":["spring","summer"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/sunflower/crop.png","type":"crop"},
  {"name":"Sunpetal Seed","seedIcon":"data:image/webp;base64,UklGRlQAAABXRUJQVlA4TEcAAAAvBUABECdAkG0zf5g5zOAaNyKQtFn/SGMN3ukQZhsNZBjz9zmE+81/AHxTa76DgjZS2CxLARJAAi+AFdH/oO8Ogy9yv+yfAAA=","seasons":["autumn","spring","summer","winter"],"treeIconUrl":"","type":"flower"},
  {"name":"Tomato Seed","seedIcon":"data:image/webp;base64,UklGRkYAAABXRUJQVlA4TDkAAAAvBUABEB+gkG0EODSg+zhOIEAYEOD/Q5tAIMVD7NH8B+SrNoFCAECb/pULssENIZOI/seDo+vvq4MA","seasons":["autumn","spring"],"treeIconUrl":"data:image/webp;base64,UklGRowAAABXRUJQVlA4TH8AAAAvCYACEE9gqAEhJXxNAQVMmOtf4moohCTJOYGcT+dY3vpl1DSSAt0dT48KHFDiXwUVQuY/ALDdRpdJ4uY6998/4ZXaANPa2pt8Klh2qLZ7ZuBfICrxtO/X1H+FbB7R/5gBQMYCEJlWtNNvmSx3UmmupP1vpjnNoicZcZIOPgQAAA==","type":"fruit"},
  {"name":"Turnip Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/turnip/seed.png","seasons":["winter"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/turnip/crop.png","type":"crop"},
  {"name":"Wheat Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/wheat/seed.png","seasons":["autumn","spring","summer","winter"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/wheat/crop.png","type":"crop"},
  {"name":"Yam Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/yam/seed.png","seasons":["autumn"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/yam/crop.png","type":"crop"},
  {"name":"Zucchini Seed","seedIcon":"https://sunflower-land.com/game-assets/crops/zucchini/seed.png","seasons":["summer"],"treeIconUrl":"https://sunflower-land.com/game-assets/crops/zucchini/crop.png","type":"crop"},
  {"name":"Orange Seed","seedIcon":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAAD1BMVEUAAAD+rjT143v+52H/8Z0Uh7ElAAAAAXRSTlMAQObYZgAAADJJREFUCNdjYBAUZGBgYDQ2FmBgEDZSNgSSSkpADpBUAZJGQBIoq+QCknZxBCkVFGAAAHIiBFdUjbgHAAAAAElFTkSuQmCC","seasons":["spring","summer"],"treeIconUrl":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAYAAABWdVznAAAAAXNSR0IArs4c6QAAAM1JREFUKJGFkD8OAUEUh79hmo0b0IhCaZttNXsAoncDap1e9BIHcAGFdiW029hEQyJR4AKExMYqZMaMXfyq+fN9894bwZ9U236i1ptJIKR5ee1VEnPvHsvUOwXjxE+kCUvvgWzWAJi39tT7BbaLu1VRpuDDCoDZuchydLHgzSQQUsGAhuNQALBu7JDeq8vbOI8D5LIGlV7CoHvSsJlMQUk6JdeeQSUORSYYTyP9tiWY/QMQRqnKAt6/9C1xmMMZ7oQWfkkmbAlK+hRMGOAJOLpMxjYgUowAAAAASUVORK5CYII=","type":"fruit"}
]);
function seedCatalogSource(value){
  const source=String(value||'').trim().replace(/\s+/g,'');
  if(/^data:image\/[^;]+;base64,/i.test(source))return source.replace(/^data:image\/[^;]+;base64,/i,'base64:');
  const assetPath=source.match(/\/game-assets\/[^?#]+/i)?.[0];
  return (assetPath||source.replace(/[?#].*$/,'')).toLowerCase();
}
function findSeedCatalogEntryFromBettyIcon(icon){const source=seedCatalogSource(icon);if(!source)return null;return SUNFLOWER_SEED_CATALOG.find(entry=>seedCatalogSource(entry.treeIconUrl)===source||seedCatalogSource(entry.seedIcon)===source)||null}
function findSeedCatalogEntryByName(name){const wanted=String(name||'').trim().toLowerCase();return SUNFLOWER_SEED_CATALOG.find(entry=>String(entry.name||'').trim().toLowerCase()===wanted)||null}
const SUNFLOWER_GREENHOUSE_SEED_ICONS=Object.freeze([
  'data:image/webp;base64,UklGRooAAABXRUJQVlA4TH0AAAAvC8ACED+gJgASNkwMOoCrgHW8VRDJBh19Px0UoIAcFLVtxLS3nodgkTn+kE7zHwBo7+BFhx33tfjlLoFVZFttld03McArwC8S0hwkBmgSHhKI6H/gBAB8BxPOXzyjvBwZRXbdhLrqolBnnVQzM1NNnj3X6MlT4BlnBJiZAAA=',
  'data:image/webp;base64,UklGRn4AAABXRUJQVlA4THIAAAAvDAADEDdAqIFxhVTQ39fU0IdMwGIxFFBPWilEcCmIZIN6P/rnkEQKISSY/wDYZr/S8zyp2QWsIkl2si/+v3oKgoFkIIECLOBfBLeFhoj+G0zapu3mL3UYfI2pUXITSidiIOovIBqIYYXxSIDrpuBlpgc=',
  'data:image/webp;base64,UklGRmIAAABXRUJQVlA4TFUAAAAvCAACEC9AkG0bHMoEfoLnZAGmwQnsL4BAUtS2DRzqDWvPzX8ArFcjma/6BwWNJLX5hTfwOGgKqoI/CRDR/6BvqOUbM95lhr7N0LO5JfMdysw9wEsCAA=='
]);
function isGreenhouseSeedIcon(icon){const source=seedCatalogSource(icon);return Boolean(source)&&SUNFLOWER_GREENHOUSE_SEED_ICONS.some((entry)=>seedCatalogSource(entry)===source)}
